services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: wp-db
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - .env

  wordpress:
    platform: linux/amd64
    image: wordpress:latest
    container_name: wp-site
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    restart: always
    env_file:
      - .env

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
